# Generated by Django 3.2.3 on 2021-05-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interesting_url',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date_and_time', models.CharField(max_length=100)),
                ('interested_group', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unintresting_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
    ]
